import { spawnSync } from "node:child_process";

const commands = [
  "node --check server.js",
  "node --check app.js",
  "node scripts/check-local-course-folder-absorption-ledger.mjs",
  "node scripts/check-local-course-multi-folder-absorption-audit.mjs",
  "node scripts/check-local-course-original-folder-deletion-readiness.mjs",
  "node scripts/check-local-course-5-document-intake.mjs",
  "node scripts/check-local-course-5-container-index.mjs",
  "node scripts/check-local-course-5-zip-visual-sample-index.mjs",
  "node scripts/check-local-course-5-visual-review-queue.mjs",
  "node scripts/check-local-course-5-visual-semantic-map.mjs",
  "node scripts/check-local-course-5-module-synthesis.mjs",
  "node scripts/check-local-course-5-teaching-module-distillation.mjs",
  "node scripts/check-local-course-5-module-distillation-review-batch-index.mjs",
  "node scripts/check-local-course-5-absorption-cockpit.mjs",
  "node scripts/check-local-course-5-source-retention-manifest.mjs",
  "node scripts/check-local-course-5-ocr-visual-execution-router.mjs",
  "node scripts/check-local-course-5-zip-image-package-execution-pack.mjs",
  "node scripts/check-local-course-5-zip-machine-visual-semantic-drafts.mjs",
  "node scripts/check-local-course-5-zip-image-package-review-input-validation.mjs",
  "node scripts/check-local-course-5-zip-visual-priority-slice.mjs",
  "node scripts/check-local-course-5-zip-visual-priority-slice-input-validation.mjs",
  "node scripts/check-local-course-5-zip-visual-priority-slice-route-map.mjs",
  "node scripts/check-local-course-5-source-to-module-coverage-matrix.mjs",
  "node scripts/check-local-course-5-blocker-resolution-priority-plan.mjs",
  "node scripts/check-local-course-5-wave-1-p0-execution-pack.mjs",
  "node scripts/check-local-course-5-wave-1-p0-reviewer-input-validation.mjs",
  "node scripts/check-local-course-5-wave-1-p0-post-input-route-map.mjs",
  "node scripts/check-local-course-5-wave-1-p0-ai-visual-review-pilot.mjs",
  "node scripts/check-local-course-5-wave-2-p1-execution-pack.mjs",
  "node scripts/check-local-course-5-wave-2-p1-reviewer-input-validation.mjs",
  "node scripts/check-local-course-5-wave-2-p1-post-input-route-map.mjs",
  "node scripts/check-local-course-5-wave-2-p1-ai-visual-review-pilot.mjs",
  "node scripts/check-local-course-5-wave-3-zip-execution-pack.mjs",
  "node scripts/check-local-course-5-wave-3-zip-reviewer-input-validation.mjs",
  "node scripts/check-local-course-5-wave-3-zip-post-input-route-map.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-batch-001.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-batch-002.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-batch-003.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-batch-004.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-batch-005.mjs",
  "node scripts/check-local-course-5-wave-3-zip-ai-visual-review-coverage-audit.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-execution-pack.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-reviewer-input-validation.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-ai-visual-review-batch-001.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-ai-visual-review-batch-002.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-ai-visual-review-batch-003.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-ai-visual-review-coverage-audit.mjs",
  "node scripts/check-local-course-5-wave-4-pdf-post-input-route-map.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-execution-pack.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-reviewer-input-validation.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-001.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-002.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-003.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-004.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-005.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-006.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-batch-007.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-ai-visual-review-coverage-audit.mjs",
  "node scripts/check-local-course-5-wave-5-pdf-post-input-route-map.mjs",
  "node scripts/check-local-course-5-wave-closure-audit.mjs",
  "node scripts/check-local-course-5-pdf-ocr-visual-execution-pack.mjs",
  "node scripts/check-local-course-5-pdf-machine-visual-semantic-drafts.mjs",
  "node scripts/check-local-course-5-pdf-ocr-visual-review-input-validation.mjs",
  "node scripts/check-local-course-5-followup-closure-cockpit.mjs",
  "node scripts/check-local-course-5-ocr-capability-preflight.mjs",
  "node scripts/check-local-course-5-pdf-ocr-priority-slice.mjs",
  "node scripts/check-local-course-5-pdf-ocr-priority-slice-input-validation.mjs",
  "node scripts/check-local-course-5-pdf-ocr-priority-slice-route-map.mjs",
  "node scripts/check-local-course-5-followup-work-packs.mjs",
  "node scripts/check-local-course-5-deletion-readiness.mjs",
  "node scripts/check-local-course-5-p0-visual-evidence-pack.mjs",
  "node scripts/check-local-course-5-p0-visual-reviewer-workbench.mjs",
  "node scripts/check-local-course-5-p0-machine-visual-semantic-drafts.mjs",
  "node scripts/check-local-course-5-non-p0-visual-reviewer-workbench.mjs",
  "node scripts/check-local-course-5-non-p0-machine-visual-semantic-drafts.mjs",
  "node scripts/check-local-course-5-followup-absorption-control-audit.mjs",
  "node scripts/check-local-course-5-followup-real-reviewer-input-template.mjs",
  "node scripts/check-local-course-5-followup-ai-review-draft-batch-001.mjs",
  "node scripts/check-local-course-5-followup-accelerated-ai-absorption.mjs",
  "node scripts/check-local-course-5-followup-ai-absorption-coverage-audit.mjs",
  "node scripts/check-local-course-5-followup-ai-module-knowledge-map.mjs",
  "node scripts/check-local-course-5-followup-ai-module-lesson-seeds.mjs",
  "node scripts/check-local-course-5-followup-knowledge-nodes.mjs",
  "node scripts/check-knowledge-sedimentation-teachable-module-audit.mjs",
  "node scripts/check-knowledge-ai-only-teaching-precheck.mjs",
  "node scripts/check-knowledge-internal-teaching-packages.mjs",
  "node scripts/check-knowledge-master-database-ai-only.mjs",
  "node scripts/check-local-video-course-source-inventory.mjs",
  "node scripts/check-local-video-course-knowledge-intake.mjs",
  "node scripts/check-local-video-course-transcript-status.mjs",
  "node scripts/check-local-video-course-semantic-absorption.mjs",
  "node scripts/check-local-video-course-knowledge-node-candidates.mjs",
  "node scripts/check-local-video-course-review-queue.mjs",
  "node scripts/check-local-video-course-coverage-audit.mjs",
  "node scripts/check-local-video-course-visual-frame-index.mjs",
  "node scripts/check-local-video-course-visual-semantic-map.mjs",
  "node scripts/check-local-video-course-visual-review-queue.mjs",
  "node scripts/check-local-video-course-delete-readiness-after-visual-audit.mjs",
  "node scripts/check-public-source-coverage-ledger.mjs",
  "node scripts/check-knowledge-base-readiness-gate.mjs",
  "node scripts/check-knowledge-module-review-cockpit.mjs",
  "node scripts/check-knowledge-reviewer-action-queue.mjs",
  "node scripts/check-knowledge-first-reviewer-action-handoff.mjs",
  "node scripts/check-knowledge-first-reviewer-field-map.mjs",
  "node scripts/check-knowledge-first-reviewer-completion-gate.mjs",
  "node scripts/check-knowledge-first-reviewer-execution-checklist.mjs",
  "node scripts/check-knowledge-first-reviewer-workbench.mjs",
  "node scripts/check-knowledge-first-reviewer-card-status-matrix.mjs",
  "node scripts/check-knowledge-first-reviewer-post-input-route-map.mjs",
  "node scripts/check-knowledge-first-reviewer-input-queue.mjs",
  "node scripts/check-knowledge-release-blocker-audit.mjs",
  "node scripts/check-knowledge-course-path-readiness-audit.mjs",
  "node scripts/check-knowledge-module-review-sprint-plan.mjs",
  "node scripts/check-local-course-high-risk-review-cockpit.mjs",
  "node scripts/check-knowledge-node-public-source-fit-real-reviewer-launch-dashboard.mjs",
  "node scripts/check-knowledge-node-public-source-fit-packet-001-reviewer-workbench.mjs",
  "node scripts/check-knowledge-node-public-source-fit-reviewer-workbench-index.mjs",
  "node scripts/check-knowledge-node-public-source-fit-reviewer-row-browser.mjs",
  "node scripts/verify-api.mjs"
];

for (const command of commands) {
  console.log(`\n$ ${command}`);
  const child = spawnSync(command, { shell: true, stdio: "inherit" });
  if (child.status !== 0) {
    process.exit(child.status ?? 1);
  }
}
